

#if !defined (PDUR_CFG_H)
#define PDUR_CFG_H

#include "Types_SwcServicePduR.hpp"

#ifndef PDUR_USE_DUMMY_STATEMENT
#define PDUR_USE_DUMMY_STATEMENT STD_ON
#endif
#ifndef PDUR_DUMMY_STATEMENT
#define PDUR_DUMMY_STATEMENT(v) (v)=(v)
#endif
#ifndef PDUR_DUMMY_STATEMENT_CONST
#define PDUR_DUMMY_STATEMENT_CONST(v) (void)(v)
#endif
#ifndef PDUR_ATOMIC_BIT_ACCESS_IN_BITFIELD
#define PDUR_ATOMIC_BIT_ACCESS_IN_BITFIELD STD_OFF
#endif
#ifndef PDUR_ATOMIC_VARIABLE_ACCESS
#define PDUR_ATOMIC_VARIABLE_ACCESS 32u
#endif
#ifndef PDUR_PROCESSOR_RH850_1013
#define PDUR_PROCESSOR_RH850_1013
#endif
#ifndef PDUR_COMP_GREENHILLS
#define PDUR_COMP_GREENHILLS
#endif
#ifndef PDUR_GEN_GENERATOR_MSR
#define PDUR_GEN_GENERATOR_MSR
#endif
#ifndef PDUR_CPUTYPE_BITORDER_LSB2MSB
#define PDUR_CPUTYPE_BITORDER_LSB2MSB
#endif
#ifndef PDUR_CONFIGURATION_VARIANT_PRECOMPILE
#define PDUR_CONFIGURATION_VARIANT_PRECOMPILE 1
#endif
#ifndef PDUR_CONFIGURATION_VARIANT_LINKTIME
#define PDUR_CONFIGURATION_VARIANT_LINKTIME 2
#endif
#ifndef PDUR_CONFIGURATION_VARIANT_POSTBUILD_LOADABLE
#define PDUR_CONFIGURATION_VARIANT_POSTBUILD_LOADABLE 3
#endif
#ifndef PDUR_CONFIGURATION_VARIANT
#define PDUR_CONFIGURATION_VARIANT PDUR_CONFIGURATION_VARIANT_PRECOMPILE
#endif
#ifndef PDUR_POSTBUILD_VARIANT_SUPPORT
#define PDUR_POSTBUILD_VARIANT_SUPPORT STD_OFF
#endif

#define PDUR_DEV_ERROR_DETECT STD_ON
#define PDUR_DEV_ERROR_REPORT STD_ON

#define PDUR_METADATA_SUPPORT STD_OFF
#define PDUR_VERSION_INFO_API STD_OFF

#define PDUR_ERROR_NOTIFICATION STD_OFF

#define PDUR_MAIN_FUNCTION STD_OFF

#define PDUR_MULTICORE STD_OFF

#define PduR_PBConfigIdType uint32

#define PDUR_FCT_CANTPRXIND 0x05u
#define PDUR_FCT_CANTPTX 0x09u
#define PDUR_FCT_CANTPTXCFM 0x08u
#define PDUR_FCT_CANTPSOR 0x06u
#define PDUR_FCT_CANTPCPYRX 0x04u
#define PDUR_FCT_CANTPCPYTX 0x07u
#define PDUR_FCT_DCMTX 0x99u
#define PDUR_FCT_CANIFRXIND 0x01u
#define PDUR_FCT_CANIFTX 0x09u
#define PDUR_FCT_CANIFTXCFM 0x02u
#define PDUR_FCT_MYCOM_BL_STATUS_MSGTX 0xC9u

#define PduRConf_PduRSrcPdu_PduRSrcPdu_83bcc558                       1u
#define PduRConf_PduRSrcPdu_PduRSrcPdu_75211821                       0u

#define PduRConf_PduRDestPdu_BootId_oP1951001_0_003_01_24_RAJA_A1_V_3098033a_Tx 0u

#define PduRConf_PduRDestPdu_UDS_Rx_Functional_oP1951001_0_003_01_24_RAJA_A1_V_554b448d_Rx_985a394f_Rx 0u
#define PduRConf_PduRDestPdu_UDS_Rx_Physical_oP1951001_0_003_01_24_RAJA_A1_V_f138e866_Rx_096fbb61_Rx 1u

#define PduRConf_PduRSrcPdu_PduRSrcPdu_096fbb61                       1u
#define PduRConf_PduRSrcPdu_PduRSrcPdu_985a394f                       0u

#define PduRConf_PduRDestPdu_UDS_Tx_Physical_oP1951001_0_003_01_24_RAJA_A1_V_abd46ddc_Tx 0u

#endif

