#if !defined (MYCOM_BL_STATUS_MSG_CBK_H)
# define MYCOM_BL_STATUS_MSG_CBK_H
#ifdef __cplusplus
extern "C"
{
#endif

# include "Types_SwcServiceCom.hpp"

#ifndef MYCOM_BL_STATUS_MSG_USE_DUMMY_STATEMENT
#define MYCOM_BL_STATUS_MSG_USE_DUMMY_STATEMENT STD_ON
#endif
#ifndef MYCOM_BL_STATUS_MSG_DUMMY_STATEMENT
#define MYCOM_BL_STATUS_MSG_DUMMY_STATEMENT(v) (v)=(v)
#endif
#ifndef MYCOM_BL_STATUS_MSG_DUMMY_STATEMENT_CONST
#define MYCOM_BL_STATUS_MSG_DUMMY_STATEMENT_CONST(v) (void)(v)
#endif
#ifndef MYCOM_BL_STATUS_MSG_ATOMIC_BIT_ACCESS_IN_BITFIELD
#define MYCOM_BL_STATUS_MSG_ATOMIC_BIT_ACCESS_IN_BITFIELD STD_OFF
#endif
#ifndef MYCOM_BL_STATUS_MSG_ATOMIC_VARIABLE_ACCESS
#define MYCOM_BL_STATUS_MSG_ATOMIC_VARIABLE_ACCESS 32u
#endif
#ifndef MYCOM_BL_STATUS_MSG_PROCESSOR_RH850_1013
#define MYCOM_BL_STATUS_MSG_PROCESSOR_RH850_1013
#endif
#ifndef MYCOM_BL_STATUS_MSG_COMP_GREENHILLS
#define MYCOM_BL_STATUS_MSG_COMP_GREENHILLS
#endif
#ifndef MYCOM_BL_STATUS_MSG_GEN_GENERATOR_MSR
#define MYCOM_BL_STATUS_MSG_GEN_GENERATOR_MSR
#endif
#ifndef MYCOM_BL_STATUS_MSG_CPUTYPE_BITORDER_LSB2MSB
#define MYCOM_BL_STATUS_MSG_CPUTYPE_BITORDER_LSB2MSB
#endif
#ifndef MYCOM_BL_STATUS_MSG_CONFIGURATION_VARIANT_PRECOMPILE
#define MYCOM_BL_STATUS_MSG_CONFIGURATION_VARIANT_PRECOMPILE 1
#endif
#ifndef MYCOM_BL_STATUS_MSG_CONFIGURATION_VARIANT_LINKTIME
#define MYCOM_BL_STATUS_MSG_CONFIGURATION_VARIANT_LINKTIME 2
#endif
#ifndef MYCOM_BL_STATUS_MSG_CONFIGURATION_VARIANT_POSTBUILD_LOADABLE
#define MYCOM_BL_STATUS_MSG_CONFIGURATION_VARIANT_POSTBUILD_LOADABLE 3
#endif
#ifndef MYCOM_BL_STATUS_MSG_CONFIGURATION_VARIANT
#define MYCOM_BL_STATUS_MSG_CONFIGURATION_VARIANT MYCOM_BL_STATUS_MSG_CONFIGURATION_VARIANT_PRECOMPILE
#endif
#ifndef MYCOM_BL_STATUS_MSG_POSTBUILD_VARIANT_SUPPORT
#define MYCOM_BL_STATUS_MSG_POSTBUILD_VARIANT_SUPPORT STD_OFF
#endif

#define MYCOM_BL_STATUS_MSG_COMIF  STD_OFF
#define MYCOM_BL_STATUS_MSG_COMIF_RX  STD_OFF
#define MYCOM_BL_STATUS_MSG_COMIF_TX  STD_OFF
#define MYCOM_BL_STATUS_MSG_COMIF_TRIGGERTRANSMIT  STD_OFF
#define MYCOM_BL_STATUS_MSG_PDUR_UL_COMIF  STD_ON
#define MYCOM_BL_STATUS_MSG_PDUR_UL_COMIF_TRIGGERTRANSMIT  STD_OFF
#define MYCOM_BL_STATUS_MSG_PDUR_UL_COMTP  STD_OFF
#define MYCOM_BL_STATUS_MSG_PDUR_LL_COMIF  STD_OFF
#define MYCOM_BL_STATUS_MSG_PDUR_LL_COMIF_TRIGGERTRANSMIT  STD_OFF
#define MYCOM_BL_STATUS_MSG_PDUR_LL_COMTP  STD_OFF
#define MYCOM_BL_STATUS_MSG_SOADUL_COMIF_RX  STD_OFF
#define MYCOM_BL_STATUS_MSG_SOADUL_COMIF_TRIGGERTRANSMIT  STD_OFF
#define MYCOM_BL_STATUS_MSG_SOADUL_COMIF_TXCONFIRMATION   STD_OFF
#define MYCOM_BL_STATUS_MSG_SOADUL_COMTP_RX  STD_OFF
#define MYCOM_BL_STATUS_MSG_SOADUL_COMTP_TX  STD_OFF
#define MyCom_Bl_Status_MsgConf_CddPduRUpperLayerTxPdu_BootId_oP1951001_0_003_01_24_Rivian_A1_V_f6c6c016_Tx 0

# define MYCOM_BL_STATUS_MSG_START_SEC_CODE
# include "MemMap.hpp"
extern FUNC(void, MYCOM_BL_STATUS_MSG_CODE) MyCom_Bl_Status_Msg_RxIndication(PduIdType RxPduId, P2CONST(PduInfoType, AUTOMATIC, MYCOM_BL_STATUS_MSG_APPL_DATA) PduInfoPtr);
extern FUNC(void, MYCOM_BL_STATUS_MSG_CODE) MyCom_Bl_Status_Msg_TxConfirmation(PduIdType TxPduId);
#if(MYCOM_BL_STATUS_MSG_PDUR_UL_COMIF_TRIGGERTRANSMIT == STD_ON)
FUNC(Std_ReturnType, MYCOM_BL_STATUS_MSG_CODE) MyCom_Bl_Status_Msg_TriggerTransmit(PduIdType TxPduId, P2VAR(PduInfoType, AUTOMATIC, MYCOM_BL_STATUS_MSG_APPL_DATA) PduInfoPtr);
#endif
# define MYCOM_BL_STATUS_MSG_STOP_SEC_CODE
# include "MemMap.hpp"

#ifdef __cplusplus
}
#endif
#endif

