#ifndef COMPILER_CFG_H
#define COMPILER_CFG_H

#define AUTOSAR_COMSTACKDATA

#define MSR_REGSPACE  REGSPACE

#define REGSPACE

#define _STATIC_   STATIC
#define _INLINE_   INLINE

#define _CDD_CODE
#define _CDD_APPL_DATA

#define CAN_CODE
#define CAN_STATIC_CODE
#define CAN_CONST
#define CAN_CONST_PBCFG
#define CAN_VAR_NOINIT
#define CAN_VAR_INIT
#define CAN_VAR_PBCFG
#define CAN_INT_CTRL
#define CAN_REG_CANCELL
#define CAN_RX_TX_DATA
#define CAN_APPL_CODE
#define CAN_APPL_CONST
#define CAN_APPL_VAR
#define CAN_VAR_FAR
#define CAN_VAR_NEAR
#define CAN_PBCFG            CAN_CONST_PBCFG

#define ECUM_CODE

#define COMM_CODE

#define FBLBMHDR_CONST
#define FBLBMHDR_CODE

#define FBLBM_CONST

#define FBLCW_CONST
#define FBLCW_PBCFG
#define FBLCW_VAR_PBCFG
#define FBLCW_CODE
#define FBLCW_VAR_NOINIT
#define FBLCW_VAR_ZERO_INIT
#define FBLCW_VAR_INIT
#define FBLCW_APPL_CODE
#define FBLCW_APPL_VAR
#define FBLCW_APPL_DATA

#define PDUR_CODE
#define PDUR_VAR_NOINIT
#define PDUR_VAR_ZERO_INIT
#define PDUR_VAR
#define PDUR_CONST
#define PDUR_PBCFG
#define PDUR_VAR_PBCFG
#define PDUR_APPL_DATA
#define PDUR_APPL_CODE

#define CANIF_CODE
#define CANIF_CODE_FAST
#define CANIF_CODE_ISR
#define CANIF_CONST
#define CANIF_CONST_FAST
#define CANIF_PBCFG
#define CANIF_VAR_PBCFG
#define CANIF_VAR_INIT
#define CANIF_VAR_NOINIT
#define CANIF_VAR_ZERO_INIT
#define CANIF_VAR_INIT_FAST
#define CANIF_VAR_NOINIT_FAST
#define CANIF_VAR_ZERO_INIT_FAST
#define CANIF_VAR_INIT_NOCACHE
#define CANIF_VAR_NOINIT_NOCACHE
#define CANIF_VAR_ZERO_INIT_NOCACHE
#define CANIF_APPL_CODE
#define CANIF_APPL_VAR
#define CANIF_APPL_PBCFG
#define CANIF_VAR_STACK
#define CANIF_APPL_STATE_VAR   CANIF_APPL_VAR
#define CANIF_APPL_MSG_VAR     CANIF_APPL_VAR
#define CANIF_CBK_VAR          CANIF_APPL_VAR
#define CANIF_CBK_DRV_VAR      CANIF_CBK_VAR
#define CANIF_CBK_TRCV_CODE     CANIF_APPL_CODE
#define CANIF_CBK_CANDRV_CODE   CANIF_APPL_CODE
#define CANIF_APPL_STATE_CODE   CANIF_APPL_CODE
#define CANIF_APPL_MSG_CODE     CANIF_APPL_CODE
#define CANIF_UL_STANDARD_VAR    CANIF_APPL_VAR
#define CANIF_UL_ADVANCED_VAR    CANIF_APPL_VAR
#define CANIF_UL_OSEKNM_VAR      CANIF_APPL_VAR

#define DET_CODE
#define DET_VAR
#define DET_APPL_DATA
#define DET_CONST

#define CRYPTOCV_CODE
#define CRYPTOCV_APPL_CONST
#define CRYPTOCV_APPL_VAR

#define WRAPNV_CODE
#define WRAPNV_VAR_NOINIT
#define WRAPNV_CONST
#define WRAPNV_DATA

#define CANTP_CODE
#define CANTP_CONST
#define CANTP_PBCFG
#define CANTP_VAR_PBCFG
#define CANTP_VAR_INIT
#define CANTP_VAR_NOINIT
#define CANTP_APPL_CODE
#define CANTP_APPL_DATA

#define VSTDLIB_CODE
#define VSTDLIB_VAR_FAR
#define VSTDLIB_APPL_VAR

#endif

